# Generated by Django 2.0.5 on 2018-05-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosnu', '0002_lecture_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=2000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosnu.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosnu.Author')),
            ],
        ),
    ]
