# Generated by Django 2.0.5 on 2018-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosnu', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote_articles', to='cosnu.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote_articles', to='cosnu.Author'),
        ),
    ]
