# Generated by Django 2.0.5 on 2018-06-07 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosnu', '0004_auto_20180604_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
