# Generated by Django 2.0.6 on 2018-06-09 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosnu', '0006_lecture_credit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('user', 'lecture')},
        ),
    ]
