# Generated by Django 2.0.6 on 2018-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosnu', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
